export const LinkTitles = {
    home: "Home",
    blog: "Blog",
    snippets: "Snippets",
    projects: "Projects",
    about: "About",
    guestbook: "Guestbook",
    tags: "Tags",
    uses: "Uses",
    now: "Now",
    stats: "Stats",
    activity: "Activity",
    recommends: "Recommends",
    journey: "Journey",
    quotes: "Quotes",
    tweets: "Tweets",
    rss: "RSS",
    resume: "Resume",
    contact: "Contact",
    signin: "Sign In"
};
