export const LinkTitles = {
    home: "Home",
    blog: "Blog",
    snippets: "Snippets",
    hireMe: "Hire Me",
    projects: "Projects",
    about: "About",
    guestbook: "Guestbook",
    siteMap: "Site Map",
    tags: "Tags",
    uses: "Uses",
    now: "Now",
    stats: "Stats",
    activity: "Activity",
    recommends: "Recommends",
    journey: "Journey",
    quotes: "Quotes",
    tweets: "Tweets",
    rss: "RSS",
    resume: "Resume",
    contact: "Contact",
    signin: "Sign In",
    instagram: "Instagram",
    youtube: "YouTube",
    reachme: "Reach Me",
    linkedin: "LinkedIn",
    github: "GitHub",
    facebook: "Facebook",
    twitter: "Twitter",
    medium: "Medium",
    threads: "Threads"
};