export const routes = {
    home: "/",
    about: "/about",
    blog: "/blog",
    resume: "/resume",
    cvPreview: "/cv-preview",
    contact: "/contact",
    snippets: "/snippets",
    projects: "/projects",
    guestbook: "/guestbook",
    tags: "/tags",
    uses: "/uses",
    now: "/now",
    stats: "/stats",
    activity: "/activity",
    recommends: "/recommends",
    journey: "/journey",
    quotes: "/quotes",
    tweets: "/tweets",
    rss: "/feed.xml",
    signin: "/sign-in",
};
